//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Spacecraft Controller/SpacecraftInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace AcePerinova.Controller
{
    public partial class @SpacecraftInputs : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @SpacecraftInputs()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""SpacecraftInputs"",
    ""maps"": [
        {
            ""name"": ""Flight"",
            ""id"": ""e00e5e13-67c9-43d9-a04c-af04bfd6f0a6"",
            ""actions"": [
                {
                    ""name"": ""Torque"",
                    ""type"": ""Value"",
                    ""id"": ""ea0cb1d4-ba5c-4e3e-8f88-2015b960b1f8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""InvertVector2(invertY=false)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Yaw"",
                    ""type"": ""Value"",
                    ""id"": ""496975e5-c8d0-4a0c-a695-c172af0ca406"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Thrust"",
                    ""type"": ""Button"",
                    ""id"": ""7d49b73c-c20d-4293-b1cc-cca9e6599ab5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Button"",
                    ""id"": ""e2b040bc-f9f1-4784-9a2e-a58b389b4434"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""e5be9df5-4d38-4da4-972f-0415c3f4b822"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tab"",
                    ""type"": ""Button"",
                    ""id"": ""aa001128-1b72-4801-bb72-1200173b07a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraOrientation"",
                    ""type"": ""Value"",
                    ""id"": ""17102f9d-86ba-4872-92cf-98c1ec52cf91"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""InvertVector2(invertX=false)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""d9f0ff3f-ef33-4cbc-9377-3f7e0a06e4dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""c9955c71-a275-4afd-a1af-a5b47b9ce67b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Torque"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a3785a48-b267-4309-9ec9-c534e4aa62d2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Torque"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""543c10f5-1d96-4d2a-81be-00a137808a1b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Torque"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""752e864c-3782-4c5a-9431-960e43592d49"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Torque"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""08902598-2659-4f6d-9548-5a0ad5814574"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Torque"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1aa05dfb-8acb-4e72-af73-c02032845949"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Torque"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""d195ef3f-c53a-49ff-92b3-d2512c098735"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""29ad9329-5d88-4869-a7f0-5497988fb605"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4a15e425-5922-4ed5-8970-4a84b58f9fab"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""88dedd73-bc2e-472a-b8d8-77fff78f8c14"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""191af3f0-a374-4821-b5de-8b8f28954cff"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""29bac266-247d-4139-b50e-bfd39cc6c530"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""16486782-b352-434a-a418-d0457b1325fa"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48149970-60d9-4371-88b1-342c8f69b5fc"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0932f71-e781-44ef-9c29-7f214da36c57"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f718eac3-5fac-4465-8499-59c1f534f8aa"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""486b4165-068e-4073-a91e-063cd8be8f26"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6de73582-f998-4a5d-9168-76bb4e1717c3"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f192c22-7057-48e0-8375-05622cf59cf4"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""682221c7-5cf1-41d1-ba3a-84d62ae24d84"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c644a39-89f5-4fef-abd4-78ac86f2e82d"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8789e0e0-4d75-4d31-acb6-a4d15d66d7cb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraOrientation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c745d080-ec61-4fdb-83b4-d8b592df83ee"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ba38a97e-2de2-4e7a-9d0c-d66fc90e09d4"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d3a946c6-345a-4d7e-883e-b01d8d1a1555"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""23ff6ff7-8ed6-4332-96c6-8146e6912fce"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""62b35fc6-01de-4d90-a4f1-f7650cb5138b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de92ffc0-bcf6-4ac5-92a0-745f0f58cef2"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Flight
            m_Flight = asset.FindActionMap("Flight", throwIfNotFound: true);
            m_Flight_Torque = m_Flight.FindAction("Torque", throwIfNotFound: true);
            m_Flight_Yaw = m_Flight.FindAction("Yaw", throwIfNotFound: true);
            m_Flight_Thrust = m_Flight.FindAction("Thrust", throwIfNotFound: true);
            m_Flight_Brake = m_Flight.FindAction("Brake", throwIfNotFound: true);
            m_Flight_Start = m_Flight.FindAction("Start", throwIfNotFound: true);
            m_Flight_Tab = m_Flight.FindAction("Tab", throwIfNotFound: true);
            m_Flight_CameraOrientation = m_Flight.FindAction("CameraOrientation", throwIfNotFound: true);
            m_Flight_PrimaryWeapon = m_Flight.FindAction("PrimaryWeapon", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Flight
        private readonly InputActionMap m_Flight;
        private IFlightActions m_FlightActionsCallbackInterface;
        private readonly InputAction m_Flight_Torque;
        private readonly InputAction m_Flight_Yaw;
        private readonly InputAction m_Flight_Thrust;
        private readonly InputAction m_Flight_Brake;
        private readonly InputAction m_Flight_Start;
        private readonly InputAction m_Flight_Tab;
        private readonly InputAction m_Flight_CameraOrientation;
        private readonly InputAction m_Flight_PrimaryWeapon;
        public struct FlightActions
        {
            private @SpacecraftInputs m_Wrapper;
            public FlightActions(@SpacecraftInputs wrapper) { m_Wrapper = wrapper; }
            public InputAction @Torque => m_Wrapper.m_Flight_Torque;
            public InputAction @Yaw => m_Wrapper.m_Flight_Yaw;
            public InputAction @Thrust => m_Wrapper.m_Flight_Thrust;
            public InputAction @Brake => m_Wrapper.m_Flight_Brake;
            public InputAction @Start => m_Wrapper.m_Flight_Start;
            public InputAction @Tab => m_Wrapper.m_Flight_Tab;
            public InputAction @CameraOrientation => m_Wrapper.m_Flight_CameraOrientation;
            public InputAction @PrimaryWeapon => m_Wrapper.m_Flight_PrimaryWeapon;
            public InputActionMap Get() { return m_Wrapper.m_Flight; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(FlightActions set) { return set.Get(); }
            public void SetCallbacks(IFlightActions instance)
            {
                if (m_Wrapper.m_FlightActionsCallbackInterface != null)
                {
                    @Torque.started -= m_Wrapper.m_FlightActionsCallbackInterface.OnTorque;
                    @Torque.performed -= m_Wrapper.m_FlightActionsCallbackInterface.OnTorque;
                    @Torque.canceled -= m_Wrapper.m_FlightActionsCallbackInterface.OnTorque;
                    @Yaw.started -= m_Wrapper.m_FlightActionsCallbackInterface.OnYaw;
                    @Yaw.performed -= m_Wrapper.m_FlightActionsCallbackInterface.OnYaw;
                    @Yaw.canceled -= m_Wrapper.m_FlightActionsCallbackInterface.OnYaw;
                    @Thrust.started -= m_Wrapper.m_FlightActionsCallbackInterface.OnThrust;
                    @Thrust.performed -= m_Wrapper.m_FlightActionsCallbackInterface.OnThrust;
                    @Thrust.canceled -= m_Wrapper.m_FlightActionsCallbackInterface.OnThrust;
                    @Brake.started -= m_Wrapper.m_FlightActionsCallbackInterface.OnBrake;
                    @Brake.performed -= m_Wrapper.m_FlightActionsCallbackInterface.OnBrake;
                    @Brake.canceled -= m_Wrapper.m_FlightActionsCallbackInterface.OnBrake;
                    @Start.started -= m_Wrapper.m_FlightActionsCallbackInterface.OnStart;
                    @Start.performed -= m_Wrapper.m_FlightActionsCallbackInterface.OnStart;
                    @Start.canceled -= m_Wrapper.m_FlightActionsCallbackInterface.OnStart;
                    @Tab.started -= m_Wrapper.m_FlightActionsCallbackInterface.OnTab;
                    @Tab.performed -= m_Wrapper.m_FlightActionsCallbackInterface.OnTab;
                    @Tab.canceled -= m_Wrapper.m_FlightActionsCallbackInterface.OnTab;
                    @CameraOrientation.started -= m_Wrapper.m_FlightActionsCallbackInterface.OnCameraOrientation;
                    @CameraOrientation.performed -= m_Wrapper.m_FlightActionsCallbackInterface.OnCameraOrientation;
                    @CameraOrientation.canceled -= m_Wrapper.m_FlightActionsCallbackInterface.OnCameraOrientation;
                    @PrimaryWeapon.started -= m_Wrapper.m_FlightActionsCallbackInterface.OnPrimaryWeapon;
                    @PrimaryWeapon.performed -= m_Wrapper.m_FlightActionsCallbackInterface.OnPrimaryWeapon;
                    @PrimaryWeapon.canceled -= m_Wrapper.m_FlightActionsCallbackInterface.OnPrimaryWeapon;
                }
                m_Wrapper.m_FlightActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Torque.started += instance.OnTorque;
                    @Torque.performed += instance.OnTorque;
                    @Torque.canceled += instance.OnTorque;
                    @Yaw.started += instance.OnYaw;
                    @Yaw.performed += instance.OnYaw;
                    @Yaw.canceled += instance.OnYaw;
                    @Thrust.started += instance.OnThrust;
                    @Thrust.performed += instance.OnThrust;
                    @Thrust.canceled += instance.OnThrust;
                    @Brake.started += instance.OnBrake;
                    @Brake.performed += instance.OnBrake;
                    @Brake.canceled += instance.OnBrake;
                    @Start.started += instance.OnStart;
                    @Start.performed += instance.OnStart;
                    @Start.canceled += instance.OnStart;
                    @Tab.started += instance.OnTab;
                    @Tab.performed += instance.OnTab;
                    @Tab.canceled += instance.OnTab;
                    @CameraOrientation.started += instance.OnCameraOrientation;
                    @CameraOrientation.performed += instance.OnCameraOrientation;
                    @CameraOrientation.canceled += instance.OnCameraOrientation;
                    @PrimaryWeapon.started += instance.OnPrimaryWeapon;
                    @PrimaryWeapon.performed += instance.OnPrimaryWeapon;
                    @PrimaryWeapon.canceled += instance.OnPrimaryWeapon;
                }
            }
        }
        public FlightActions @Flight => new FlightActions(this);
        public interface IFlightActions
        {
            void OnTorque(InputAction.CallbackContext context);
            void OnYaw(InputAction.CallbackContext context);
            void OnThrust(InputAction.CallbackContext context);
            void OnBrake(InputAction.CallbackContext context);
            void OnStart(InputAction.CallbackContext context);
            void OnTab(InputAction.CallbackContext context);
            void OnCameraOrientation(InputAction.CallbackContext context);
            void OnPrimaryWeapon(InputAction.CallbackContext context);
        }
    }
}
